version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      astro:
        patterns:
          - 'astro'
          - '@astrojs/*'
      react:
        patterns:
          - 'react'
          - 'react-dom'
          - '@types/react'
          - '@types/react-dom'
          - 'react-resizable-panels'
          - 'lucide-react'
      tailwind:
        patterns:
          - 'tailwindcss'
          - '@tailwindcss/*'
          - 'tailwind-merge'
      codemirror:
        patterns:
          - '@codemirror/*'
          - '@uiw/react-codemirror'
      unified:
        patterns:
          - 'unified'
          - 'remark-*'
          - 'rehype-*'
      lint-and-format:
        patterns:
          - 'eslint'
          - 'eslint-*'
          - '@typescript-eslint/*'
          - 'typescript-eslint'
          - 'prettier'
          - 'prettier-*'
      typescript:
        patterns:
          - 'typescript'
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
    groups:
      github-actions:
        patterns:
          - '*'
